<script setup>
import { useStore } from "~/stores/store";

const store = useStore();

useHead({
  script: [
    {
      src: '/lib/geoip2.js',
      id: 'geoip2',
      async: true
    }
  ]
});

// Traffic source detection
const ORGANIC_DOMAINS = new Set([
  "360.cn",
  "alice",
  "aol",
  "ask",
  "auone",
  "avg",
  "babylon",
  "baidu",
  "biglobe",
  "bing",
  "centrum.cz",
  "cnn",
  "comcast",
  "conduit",
  "daum",
  "dogpile",
  "duckduckgo",
  "ecosia",
  "eniro",
  "exalead",
  "excite",
  "firmy.cz",
  "globo",
  "google",
  "incredimail",
  "kvasir",
  "lycos",
  "mail.ru",
  "msn",
  "naver",
  "onet",
  "qwant",
  "rakuten",
  "rambler",
  "search-results",
  "seznam",
  "so.com",
  "sogou",
  "startsiden",
  "terra",
  "ukr",
  "virgilio",
  "yahoo",
  "yandex"
]);
const SOCIALS = new Set([
  "43things",
  "51.com",
  "5ch.net",
  "academia.edu",
  "activerain",
  "activeworlds",
  "addthis",
  "airg.ca",
  "allnurses.com",
  "allrecipes.com",
  "alumniclass",
  "ameba.jp",
  "ameblo.jp",
  "americantowns",
  "ancestry.com",
  "anobii",
  "answerbag",
  "aolanswers",
  "artstation.com",
  "askubuntu",
  "asmallworld.com",
  "athlinks",
  "awe.sm",
  "baby-gaga",
  "babyblog.ru",
  "badoo",
  "bebo",
  "beforeitsnews",
  "bharatstudent",
  "biip.no",
  "biswap.org",
  "bit.ly",
  "blackcareernetwork.com",
  "blackplanet",
  "blip.fm",
  "blog.com",
  "blogg.no",
  "bloggang.com",
  "blogger",
  "blogher",
  "bloglines",
  "blogs.com",
  "blogsome",
  "blogspot",
  "blogster",
  "blurtit",
  "brightkite",
  "brizzly",
  "buzzfeed",
  "buzznet",
  "cafemom",
  "camospace",
  "canalblog.com",
  "care.com",
  "care2",
  "caringbridge.org",
  "catster",
  "cbnt.io",
  "cellufun",
  "centerblog.net",
  "chegg.com",
  "chicagonow",
  "classmates",
  "classquest",
  "cocolog-nifty",
  "copainsdavant.linternaute.com",
  "couchsurfing.org",
  "cozycot",
  "cross.tv",
  "crunchyroll",
  "cyworld",
  "dailystrength.org",
  "deluxe.com",
  "deviantart",
  "dianping",
  "digg",
  "diigo",
  "disqus",
  "dogster",
  "dol2day",
  "doostang",
  "dopplr",
  "douban",
  "draugiem.lv",
  "drugs-forum",
  "dzone",
  "edublogs.org",
  "elftown",
  "epicurious.com",
  "everforo.com",
  "exblog.jp",
  "extole",
  "facebook",
  "faceparty",
  "fandom.com",
  "fanpop",
  "fark",
  "fb.me",
  "fc2",
  "feedspot",
  "feministing",
  "filmaffinity",
  "flickr",
  "flipboard",
  "folkdirect",
  "foodservice",
  "fotki",
  "fotolog",
  "foursquare",
  "friendfeed",
  "fruehstueckstreff.org",
  "fubar",
  "gaiaonline",
  "gamerdna",
  "gather.com",
  "geni.com",
  "getpocket.com",
  "glassboard",
  "glassdoor",
  "godtube",
  "goldenline.pl",
  "goldstar",
  "goo.gl",
  "gooblog",
  "goodreads",
  "govloop",
  "gowalla",
  "gree.jp",
  "gulli.com",
  "gutefrage.net",
  "habbo",
  "hatena",
  "hi5",
  "hootsuite",
  "houzz",
  "hoverspot",
  "hr.com",
  "hubculture",
  "hubpages",
  "hyves",
  "ibibo",
  "identi.ca",
  "imageshack",
  "imvu",
  "insanejournal",
  "instagram",
  "instapaper",
  "internations.org",
  "interpals.net",
  "intherooms",
  "irc-galleria.net",
  "is.gd",
  "italki",
  "jammerdirect",
  "jappy",
  "kaboodle.com",
  "kakao",
  "kaneva",
  "last.fm",
  "librarything",
  "line",
  "linkedin",
  "listal",
  "listography",
  "livedoor",
  "livejournal",
  "lnkd.in",
  "mbga.jp",
  "medium.com",
  "meetin.org",
  "meetup",
  "meinvz.net",
  "meneame.net",
  "menuism.com",
  "messenger",
  "mix.com",
  "mixi.jp",
  "mocospace",
  "mouthshut",
  "movabletype",
  "mubi",
  "myanimelist.net",
  "myheritage",
  "mylife",
  "mymodernmet",
  "myspace",
  "naver",
  "netvibes",
  "news.ycombinator.com",
  "newsshowcase",
  "nexopia",
  "ngopost.org",
  "niconico",
  "nicovideo.jp",
  "nightlifelink",
  "ning",
  "odnoklassniki",
  "okwave.jp",
  "oneworldgroup.org",
  "onstartups",
  "opendiary",
  "opera.com",
  "overblog",
  "paper.li",
  "partyflock.nl",
  "photobucket",
  "pinboard",
  "pingsta",
  "pinterest",
  "pixiv.net",
  "playahead.se",
  "plurk",
  "pocket.co",
  "posterous",
  "pro.homeadvisor.com",
  "qapacity",
  "quechup",
  "quora",
  "qzone.qq.com",
  "ravelry",
  "reddit",
  "redux",
  "renren",
  "researchgate.net",
  "reunion",
  "reverbnation",
  "rtl.de",
  "ryze",
  "salespider",
  "scoop.it",
  "screenrant",
  "scribd",
  "scvngr",
  "secondlife",
  "serverfault",
  "shareit",
  "sharethis",
  "shvoong.com",
  "skype",
  "skyrock",
  "slashdot.org",
  "slideshare.net",
  "smartnews.com",
  "snapchat",
  "sociallife.com.br",
  "socialvibe",
  "spaces.live.com",
  "spoke",
  "spruz",
  "ssense.com",
  "stackapps",
  "stackexchange",
  "stackoverflow",
  "stardoll.com",
  "stickam",
  "studivz.net",
  "suomi24.fi",
  "superuser",
  "sweeva",
  "t.co",
  "t.me",
  "tagged",
  "taggedmail",
  "talkbiznow",
  "taringa.net",
  "techmeme",
  "tencent",
  "tiktok",
  "tinyurl",
  "toolbox",
  "travellerspoint",
  "tripadvisor",
  "trombi",
  "trustpilot",
  "tudou",
  "tuenti",
  "tumblr",
  "tweetdeck",
  "twitter",
  "twoo.com",
  "typepad",
  "unblog.fr",
  "urbanspoon.com",
  "ushareit.com",
  "ushi.cn",
  "vampirefreaks",
  "vampirerave",
  "vg.no",
  "video.ibm.com",
  "vk",
  "wakoopa",
  "wattpad",
  "webshots",
  "wechat",
  "weebly",
  "weibo",
  "wer-weiss-was.de",
  "weread",
  "whatsapp",
  "wikihow.com",
  "wikitravel.org",
  "woot.com",
  "wordpress",
  "xanga",
  "xing",
  "yammer",
  "yelp",
  "youroom.in",
  "zalo",
  "zoo.gr",
  "zooppa"
]);
const LLM_DOMAINS_REGEX = /^.*ai|.*\.openai.*|.*copilot.*|.*chatgpt.*|.*gemini.*|.*gpt.*|.*neeva.*|.*writesonic.*|.*nimble.*|.*outrider.*|.*perplexity.*|.*google.*bard.*|.*bard.*google.*|.*bard.*|.*edgeservices.*|.*astastic.*|.*copy\.ai.*|.*bnngpt.*|.*gemini.*google.*$/;

function normalizeUrl(url) {
  return url
    .toLowerCase()
    .replace(/^https?:\/\//, '')
    .replace(/^www\./, '')
    .split('/')[0]
    .split(':')[0]
    .trim();
}

function getUeidByReferrer(referrer, urlParams = null) {
  if (!referrer && !urlParams.get('referrer')) return null;
  store.setVisitorInfo({ mst: 'r0TV0W_hUOqv_Uow4brhX-wkx5F9TQ' });

  const normalizedReferrer = urlParams.get('referrer')
    ? normalizeUrl(urlParams.get('referrer'))
    : normalizeUrl(referrer);
  const matchesDomain = (domain) => normalizedReferrer.includes(domain);
  if ([...SOCIALS].some(matchesDomain)) {
    return 'dpbosoc_auto';
  }

  if ([...ORGANIC_DOMAINS].some(matchesDomain)) {
    return 'dpbosrc_auto';
  }

  if (LLM_DOMAINS_REGEX.test(normalizedReferrer)) {
    return 'dpboai_auto';
  }
  return null;
}

// Run on client side only
onMounted(() => {
  const urlParams = new URLSearchParams(window.location.search);
  const ueid = urlParams.get('ueid');
  if (ueid) {
    store.setVisitorInfo({ ueid });
  } else {
    store.setVisitorInfo({ ueid: getUeidByReferrer(document.referrer, urlParams) });
  }
});
</script>
<template>
  <div id="protectApp">
    <NuxtLayout>
      <NuxtPage />
    </NuxtLayout>
  </div>
</template>
